version: '3.1'

services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/noyo -schemas=public,api -user=noyoapi -password=noyo -connectRetries=60 migrate
    volumes:
      - ./ddl:/flyway/sql
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "noyo"
      POSTGRES_PASSWORD: "noyo"
      POSTGRES_USER: "noyoapi"
    ports:
      - 5432:5432

